# Generated by Django 3.0.6 on 2020-08-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='data_mining')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'data_mining',
            },
        ),
    ]
