# Generated by Django 3.0.6 on 2020-08-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsapp', '0003_auto_20200829_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataVisualization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/data_visualization/')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='datamining',
            name='file',
            field=models.FileField(upload_to='media/data_mining/'),
        ),
    ]
