# Generated by Django 3.0.6 on 2020-08-30 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyticsapp', '0004_auto_20200830_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datamining',
            old_name='file',
            new_name='data_to_mine',
        ),
        migrations.RenameField(
            model_name='datavisualization',
            old_name='file',
            new_name='data_to_visualize',
        ),
    ]
