# Generated by Django 3.1.1 on 2020-09-23 09:27

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analyticsapp', '0008_auto_20200923_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbTables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now=True)),
                ('table_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('Dbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyticsapp.dbs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'db_tables',
            },
        ),
        migrations.DeleteModel(
            name='Tables',
        ),
    ]
